name = "rabbitsearch2"
main = "src/index.js"
compatibility_date = "2023-06-08"

[[kv_namespaces]]
binding = "KV"
id = "8e181ff489f44d55821a0768d4d262ab"

[vars]
# Don't forget to set the brave api key with: wrangler secret put BRAVE_SEARCH_KEY
# Don't forget to set the pexels api key with: wrangler secret put PEXELS_SEARCH_KEY