name = "rabbitsearch"
main = "src/index.js"
compatibility_date = "2023-02-10"

[[kv_namespaces]]
binding = "KV"
id = "69dc3dfbdb0843a4be0f762799387c12"

[vars]
# Don't forget to set the bing search key with: wrangler secret put BING_SEARCH_KEY
# Don't forget to set the bing search key with: wrangler secret put BING_IMAGES_KEY
# Don't forget to set the bing search key with: wrangler secret put BING_VIDEOS_KEY
# Don't forget to set the bing search key with: wrangler secret put BING_NEWS_KEY