name = "rabbitsearch"
main = "src/index.js"
compatibility_date = "2023-06-08"

[[kv_namespaces]]
binding = "KV"
id = "501ca2b196b1438f816c1698e3e4c5fb"

[vars]
#
# BING API SETTINGS
#
# Don't forget to set the bing search key with: wrangler secret put BING_SEARCH_KEY
# Don't forget to set the bing images key with: wrangler secret put BING_IMAGES_KEY
# Don't forget to set the bing videos key with: wrangler secret put BING_VIDEOS_KEY
# Don't forget to set the bing news key with: wrangler secret put BING_NEWS_KEY

#
# OPENAI API SETTINGS (https://openai.com/api/)
#
# Don't forget to set the openai key with: wrangler secret put OPENAI_KEY